videojuegos/usuarios/urls.py
from django.urls import path
# from articulos import views, views_categoria
from usuarios import views
from django.contrib.auth.views import LogoutView

app_name = 'usuarios'
# usuarios:logout
# usuarios:perfil

urlpatterns = [
    path('salir', LogoutView.as_view(), name='logout'),
    path('entrar', views.LoginView.as_view(), name='login'),
    path('registrar', views.RegistrarView.as_view(), name='registrar'),
    path('perfil', views.CrearPerfilView.as_view(), name='perfil'),
    path('lista', views.ListaUsuariosView.as_view(), name='lista'),
    path('grupos', views.asignar_grupos, name='asignar_grupos'),
    path('activar/<slug:uidb64>/<slug:token>', views.ActivarCuentaView.as_view(), name='activar'),
    
    path('municipios', views.busca_municipios, name='busca_municipios'),
    
]

videojuegos/videojuegos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articulos.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('encuestas/', include('encuestas.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

videojuegos/usuarios/models.py
from django.db import models
from usuarios. validadores import rfc_validador, curp_validador
from django.contrib.auth.models import User


class DatosPersonales(models.Model):
    rfc = models.CharField("R.F.C.", max_length=13, validators=[rfc_validador])
    curp = models.CharField("C.U.R.P.", max_length=18, validators=[curp_validador])
    direccion = models.CharField("Dirección", max_length=150)
    telefono = models.CharField("Teléfono", max_length=10)
    foto = models.ImageField(upload_to='perfil')
    user = models.OneToOneField(User, verbose_name="Usuario", related_name='datos', on_delete=models.DO_NOTHING)
    estado = models.ForeignKey("usuarios.Estado", verbose_name="Estado", on_delete=models.DO_NOTHING)
    municipio = models.ForeignKey("usuarios.Municipio", verbose_name="Municipio", on_delete=models.DO_NOTHING)


class Estado(models.Model):
    nombre = models.CharField(max_length=100)
    
    def __str__(self):
        return self.nombre
    
class Municipio(models.Model):
    nombre = models.CharField(max_length=100)
    estado = models.ForeignKey("usuarios.Estado", verbose_name="Estado", on_delete=models.DO_NOTHING)
    
    def __str__(self):
        return self.nombre
    

videojuegos/usuarios/forms.py
from django.urls import reverse_lazy
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from .models import DatosPersonales


class UserForm(forms.ModelForm):
    repassword = forms.CharField()
    class Meta:
        model = User
        fields = ('username','password','email','repassword')

    email = forms.EmailField(required=True)
    
    
    def save(self, commit=True):
        user = super(UserForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user
    
    def clean_password(self, *args, **kwargs):
        if self.data['password'] != self.data['repassword']:
            raise forms.ValidationError('Las contraseñas son diferentes; favor de verificar')
        
        return self.data['password']
            

class FormDatosPersonales(forms.ModelForm):
    class Meta:
        model = DatosPersonales
        # fields = '__all__'
        exclude = ['user']
        
        widgets = {
            'estado': forms.Select(attrs={
                'class':'form-control',
                'data-url':reverse_lazy('usuarios:busca_municipios')
            }),
        }

# class LoginForm(AuthenticationForm):
    
#     class Meta:
#         fields = '__all__'
        
#         widgets = {
#             'username': forms.TextInput(attrs={'class':'form-control'}),
#             'preguntaE1-A': forms.PasswordInput(attrs={'class':'form-control ocultar'}),
            
#         }
        
    

videojuegos/usuarios/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.contrib.auth.models import User, Group
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.core.mail import EmailMessage
from django.views.generic import TemplateView
from django.contrib import messages
from django.views.generic import ListView
from django.http import JsonResponse

from .models import DatosPersonales, Municipio
from .forms import UserForm, FormDatosPersonales
from .token import token_activacion

# from .forms import LoginForm


class LoginView(LoginView):
    template_name = 'login.html'
    form_class = AuthenticationForm
    # form_class = LoginForm

class ListaUsuariosView(ListView):
    model = User
    template_name = 'lista_usuarios.html'
    
    def get_context_data(self, **kwargs):
        context = super(ListaUsuariosView,self).get_context_data(**kwargs)
        context['grupos'] = Group.objects.all()
        return context

def asignar_grupos(request):
    id_usuario = request.POST.get('usuario', None)
    usuario = User.objects.get(id=id_usuario)
    
    usuario.groups.clear()
    for item in request.POST:
        if request.POST[item] == 'on':
            grupo = Group.objects.get(id=int(item))
            usuario.groups.add(grupo)
    messages.success(request, 'Se agregó el usuario a los grupos')
            
    return redirect('usuarios:lista')       

class RegistrarView(SuccessMessageMixin, CreateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy('usuarios:login')
    success_message = "%(username)s se registró de manera exitosa"
    
    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        
        # sitio = get_current_site(self.request)
        
        # uid = urlsafe_base64_encode(force_bytes(user.id))
        # token = token_activacion.make_token(user)
        # mensaje = render_to_string(
        #     'confirmar_cuenta.html',
        #     {
        #         'user': user,
        #         'sitio': sitio,
        #         'uid': uid,
        #         'token': token
        #     }
        # )
        
        # asunto = 'Activar cuenta'
        # para = user.email
        # email = EmailMessage(
        #     asunto,
        #     mensaje,
        #     to=[para],
        # )
        # email.content_subtype = 'html'
        # email.send()
        
        return super().form_valid(form)


class ActivarCuentaView(TemplateView):
    def get(self, request, *args, **kwargs):
        
        try:
            uid = urlsafe_base64_decode(kwargs['uidb64'])
            token = kwargs['token']
            user = User.objects.get(pk=uid)
        except(TypeError, ValueError, User.DoesNotExist):
            user = None
        if user is not None and token_activacion.check_token(user, token):
            user.is_active = True
            user.save()
            
            messages.success(request, 'Cuenta activada, ingresar datos')
        else:
            messages.error(request, 'Token inválido, contacta al administrador')
            
        return redirect('usuarios:login')
        
   
class CrearPerfilView(SuccessMessageMixin, CreateView):
    model = DatosPersonales
    form_class = FormDatosPersonales
    success_url = reverse_lazy('bienvenida')
    success_message = "Se guardaron tus datos personales"

    def post(self, request, *args, **kwargs):
        print(request.POST)
        
        return super().post(request, *args, **kwargs)
        
    def form_valid(self, form):
        datos_personales = form.save(commit=False)
        datos_personales.user = self.request.user
        datos_personales.save()
        
        return super().form_valid(form)
        


def busca_municipios(request):
    id_estado = request.POST.get('id_estado', None)
    if id_estado:
        municipios = Municipio.objects.filter(estado_id=id_estado)
        data = [{'id':mun.id,'nombre':mun.nombre} for mun in municipios]
        return JsonResponse(data, safe=False)
    return JsonResponse({'error':'Parámetro inválido'}, safe=False)        

videojuegos/usuarios/templates/confirmar_cuenta.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmar cuenta</title>
</head>
<body>
    <h3>Validar cuenta</h3>
    <p>Hola <b>{{user.username}}</b>:</p>
    <p>Para completar tu registro en el Sistema Videojuegos debes activar tu cuenta haciendo click en el siguiente enlace:</p>
    <br>
    <br>
    <p>
        <a href="http://{{sitio}}{% url 'usuarios:activar' uidb64=uid token=token %}">
            Activar cuenta
        </a>
    </p>
</body>
</html>

videojuegos/usuarios/templates/lista_usuarios.html
{% extends 'base.html' %}
{% load static %}


{% block titulo %}
    Lista de usuarios
{% endblock titulo %}

{% block contenido %}
    <h1>Lista de usuarios</h1>
    
    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class="alert alert-danger">
                    {{message}}
                </div>
            {% else %}
                <div class="alert alert-success">
                    {{message}}
                </div>
            {% endif %}        
        {% endfor %}
    {% endif %}
        
    <table class="table">
        <thead>
            <tr>
                <th>Nombre de usuario</th>
                <th>Nombre</th>
                <th>Apellidos</th>
                <th>RFC</th>
                <th>CURP</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for usuario in object_list  %}
                <tr>
                    <td>{{usuario.username}}</td>
                    <td>{{usuario.first_name}}</td>
                    <td>{{usuario.last_name}}</td>
                    <td>{{usuario.datos.rfc}}</td>
                    <td>{{usuario.datos.curp}}</td>
                    <td>
                        <a class="btn btn-outline-primary btn-sm" href="">Editar</a>
                        <button type="button" 
                            onclick="asignaUsuario('{{usuario.id}}', '{% for g in usuario.groups.all %}{{g.id}}-{% endfor %}')"
                            class="btn btn-success" 
                            data-usuario="{{usuario.id}}" 
                            data-grupos="{% for g in usuario.groups.all %}{{g.id}}-{% endfor %}" 
                            data-toggle="modal" 
                            data-target="#modal-grupos">
                            Grupos
                        </button>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="6">
                        <p>No existen usuarios registrados</p>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>


<div class="modal fade" id="modal-grupos">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Asignar grupos</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <form id="formGrupos" action="{% url 'usuarios:asignar_grupos' %}" method="post">
            {% csrf_token %}
            <div class="modal-body">
                {% for grupo in grupos %}
                    <p>
                        <input type="checkbox" name="{{grupo.id}}"> {{grupo.name}}
                    </p>
                {% endfor %}
            </div>
            <input type="hidden" name="usuario" id="idUsuario">
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="submit" class="btn btn-primary">Asignar grupos</button>
            </div>
        </form>
        </div>
        <!-- /.modal-content -->
    </div>
</div>

{% endblock contenido %}

{% block scripts %}
    <script src="{% static 'dist/js/funciones.js' %}"></script>
{% endblock scripts %}

videojuegos/usuarios/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Login Videojuegos</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <!-- /.login-logo -->
  <div class="card card-outline card-primary">
    <div class="card-header text-center">
      <a href="../../index2.html" class="h1"><b>Admin</b>LTE</a>
    </div>
    <div class="card-body">
      <p class="login-box-msg">Sign in to start your session</p>
      
      {% if form.errors %}
        {% comment %} {{form.errors}} {% endcomment %}
        <div class="alert alert-warning">
          Verifica tus datos de acceso.
        </div>
      {% endif %}
      {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class="alert alert-danger">
                    {{message}}
                </div>
            {% else %}
                <div class="alert alert-success">
                    {{message}}
                </div>
            {% endif %}  
        {% endfor %}
      {% endif %}
      <form method="post">
        {% csrf_token %}
        <div class="input-group mb-3">
          <input type="text" class="form-control" placeholder="Email" name="username">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" class="form-control" placeholder="Password" name="password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="remember">
              <label for="remember">
                Remember Me
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Ingresar</button>
            <input type="hidden" name="next" value="{{next}}">
          </div>
          <!-- /.col -->
        </div>
      </form>

      <div class="social-auth-links text-center mt-2 mb-3">
        <a href="#" class="btn btn-block btn-primary">
          <i class="fab fa-facebook mr-2"></i> Sign in using Facebook
        </a>
        <a href="#" class="btn btn-block btn-danger">
          <i class="fab fa-google-plus mr-2"></i> Sign in using Google+
        </a>
      </div>
      <!-- /.social-auth-links -->

      <p class="mb-1">
        <a href="forgot-password.html">I forgot my password</a>
      </p>
      <p class="mb-0">
        <a href="{% url 'usuarios:registrar' %}" class="text-center">Registrar nuevo usuario</a>
      </p>
    </div>
    <!-- /.card-body -->
  </div>
  <!-- /.card -->
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
</body>
</html>